### ISSUE TITLE
蠢面包🍞这个东西还敢拿出来考核,妈呀

### ISSUE THREAD

**Issue by LemonHX** [sectosessions/sectosessions-frontend-2019#1]

**Comment by ForeverOpp** [comment]
有一说一，这个应该是考核我这种对前端一无所知的人的。
要不就是面包推荐的入门教程/路线。

**Comment by Himself65** [comment]
的确是推荐路线，后来我没有继续更新

by Himself65
________________________________

**Comment by ForeverOpp** [comment]
我觉着更新一下挺好的，毕竟很多人入门编程就是想做个好看的界面，同时实现一些简单的功能，这些人苦于各种GUI库复杂的调用关系，同样的功能前端实现要简单很多，前端显示、后台处理数据对新手来说已经够用了。
以及还有一些想入门前端但是没有很好的路线的人，前端大佬发布的教程一般很难找（甚至不知道有哪些大佬），或者找到之后也晦涩难懂，但是面包感觉属于网红性质的前端大佬，推荐的教程很多人都会看到。
如果面包大佬把这个前端路线更新完，有一说一，很可能降低前端学习的门槛。（关注你的或多或少懂点编程但是需要人，尤其是高人指点）
